---
- debug:
    msg: "user: {{ ansible_user_id }} - fedora major version: {{ ansible_distribution_major_version }}"

- name: create user wide binary path directory 
  ansible.builtin.file:
    path: "$HOME/.local/bin"
    state: directory

- name: clear dnf cache
  become: yes
  command: dnf clean all

- name: make dnf cache
  become: yes
  command: dnf makecache

- name: update packages
  become: yes
  command: dnf update -y

- name: install packages
  become: yes
  ansible.builtin.package:
    state: latest
    name:
      - awscli2
      - flameshot
      - gimp
      - git
      - golang
      - htop
      - inkscape
      - kubernetes-client
      - make
      - openssl
      - rust
      - snapd
      - tilix
      - transmission
      - vim
      - vlc
      - youtube-dl
      - zsh

- name: enable classic snap support, enter the following to create a symbolic link between /var/lib/snapd/snap and /snap
  become: yes
  file:
    src: /var/lib/snapd/snap
    dest: /snap
    state: link

- name: install packages from snapd
  become: yes
  community.general.snap:
    classic: true
    name:
      - pycharm-community
      - code
      - telegram-desktop
